GET http://localhost:3000/cards
Accept: application/json

###
DELETE http://localhost:3000/cards/64006244346dc7533d1e8f54
Accept: application/json

###



GET http://localhost:3000/users
Accept: application/json

###

GET http://localhost:3000/users/
Accept: application/json

###

POST http://localhost:3000/users
Accept: application/json
Content-Type: application/json

###

